name: Hangar
options:
  bundleIdPrefix: com.h
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    DEVELOPMENT_TEAM: AR8U26HF34
    CODE_SIGN_STYLE: Manual
  configs:
    Debug:
      CODE_SIGN_IDENTITY: "-"
      ENABLE_HARDENED_RUNTIME: NO
    Release:
      CODE_SIGN_IDENTITY: "Developer ID Application"
      ENABLE_HARDENED_RUNTIME: YES
      OTHER_CODE_SIGN_FLAGS: "--timestamp --options=runtime"

packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    exactVersion: "2.9.2"

targets:
  Hangar:
    type: application
    platform: macOS
    sources:
      - path: Hangar
    dependencies:
      - package: Sparkle
    info:
      path: Hangar/Info.plist
      properties:
        CFBundleName: Hangar
        CFBundleDisplayName: Hangar
        CFBundleShortVersionString: "0.2.1"
        CFBundleVersion: "3"
        LSMinimumSystemVersion: "14.0"
        NSHighResolutionCapable: YES
        LSUIElement: NO
        SUFeedURL: "https://github.com/hsyvy/hangar/releases/latest/download/appcast.xml"
        SUPublicEDKey: "Vu5w4Tk0TcmU22nETzZkbXpxCsZV3Lh5vS0HL4AULqo="
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.h.hangar
        PRODUCT_NAME: Hangar
        GENERATE_INFOPLIST_FILE: NO
        ENABLE_APP_SANDBOX: NO
        CODE_SIGN_ENTITLEMENTS: Hangar/Hangar.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
